using UnityEngine;
using System.Collections;

namespace DaggerfallWorkshop.Game.Questing
{
    /// <summary>
    /// Contains an instantiated quest generated by parser.
    /// Quests can be handed to the quest machine for execution.
    /// </summary>
    public class Quest
    {
    }
}